import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#393939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'surface-variant': '#353534',
        'primary': '#9fcaff',
        'on-primary': '#003258',
        'primary-container': '#007acc',
        'on-primary-container': '#ffffff',
        'primary-fixed': '#d1e4ff',
        'primary-fixed-dim': '#9fcaff',
        'on-primary-fixed': '#001d36',
        'on-primary-fixed-variant': '#00497d',
        'inverse-primary': '#0061a4',
        'secondary': '#adc9ee',
        'on-secondary': '#133250',
        'secondary-container': '#2c4968',
        'on-secondary-container': '#9bb7dc',
        'secondary-fixed': '#d1e4ff',
        'secondary-fixed-dim': '#adc9ee',
        'on-secondary-fixed': '#001d36',
        'on-secondary-fixed-variant': '#2c4968',
        'tertiary': '#ffb784',
        'on-tertiary': '#4f2500',
        'tertiary-container': '#b95e01',
        'on-tertiary-container': '#ffffff',
        'tertiary-fixed': '#ffdcc6',
        'tertiary-fixed-dim': '#ffb784',
        'on-tertiary-fixed': '#301400',
        'on-tertiary-fixed-variant': '#713700',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'background': '#131313',
        'on-background': '#e5e2e1',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#c0c7d3',
        'outline': '#8a919d',
        'outline-variant': '#404751',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        'surface-tint': '#9fcaff',
      },
      fontFamily: {
        'headline': ['Inter', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Space Grotesk', 'sans-serif'],
        'mono': ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
    },
  },
  plugins: [],
}
export default config
